### ISSUE TITLE
List of recently used emojis is not accurate

### ISSUE THREAD

**Issue by WX4300** [oxen-io/session-android#1015]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

I see very old emojis instead of those I use the most or used lately
It seems like the old emojis are being stuck

**To reproduce**

Use emojis a lot, check that your recently used emojis aren't in the recently used row 

**Screenshots or logs**

×××

**Smartphone (please complete the following information):**

 - Device: Xiaomi Redmi Note 8 Pro
 - OS: Android 12.1
 - Version of Session or latest commit hash: 1.16.0 (3095) - F-Droid - Session's repository

**Additional context**

If it can't be solved normally, then i would recommend to replace the recently used emojis with favorite emojis picked by the users

**Comment by mdPlusPlus** [comment]
I'm having the same issue. It feels almost like the sorting is the other way around, meaning the least used (or least frequently used) emojis are listed.

It's always this for me, but I use 👍 and 💡 on a daily basis:
![image](https://user-images.githubusercontent.com/9272131/232569038-da5f099c-daca-4297-8dda-e3b3839af574.png)

**Comment by alansley** [comment]
Investigation in progress.. It looks like the most recently used emoji list isn't acting as a queue (which is how it probably should). 

As a simple example, if you had the default list of recently used emojis on a fresh install, and you use a heart emoji (which is not in the default list) then the heart should come in at the far left of the 'pill' and everything else should be pushed along to the right (with the far-right emoji dropping out of the queue). However what's happening in the current behaviour is that it's just removing any existing instance of that used emoji from anywhere in the list and then putting it back in the first slot (far left).

Another potential mechanism that could be used rather than "Recently used emoji" is "Most commonly used emoji" - because if you write a message that contains 6 unique emojis you've never used before (or let's say you use them very rarely) then it's going to completely replace the 'recently used' list - but if we kept track of the *count* of emojis used (such as via a `HashMap<String, Integer>` ) and bumped the count each time an emoji was used then if you wrote a message with a bunch of emojis you rarely used it would *not* replace the 'recently used' ones - but in effect *recently used* would become **most frequently used**.

I don't know if *most frequently used* would be preferable to *most recently used* so am very much open to feedback and suggestions. The downside might be that you can't instantly remove an emoji from a most *frequently* used list - you'd just have to use other emojis (which aren't already higher in the list) more to push it out of the list!

**Comment by alansley** [comment]
@mdPlusPlus From [your comment](https://github.com/oxen-io/session-android/issues/1015#issuecomment-1511828295) I can only guess that the saved emoji data in shared preferences has somehow become locked or corrupted (or there's a particular emoji in your list that's not being handled correctly and as such is jumping away from the 'update recent emoji list' code before it can complete). If it keeps being an issue after the next update then if we could get some logs from you to see what's happening under the hood I can look into it.

**Comment by alansley** [comment]
Regarding [the above](https://github.com/oxen-io/session-android/issues/1015#issuecomment-1899808498) it occurs that both *mostly recently used* **and** *most_commonly_used* could be implemented with a preference toggle somewhere in the settings, if we wanted. Food for thought.
