### ISSUE TITLE
No easy way to copy and share community(group) URL on Android?

### ISSUE THREAD

**Issue by slrslr** [oxen-io/session-android#1020]
**Code of conduct**

- [x ] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Hello, unlike in desktop client, Android client does not seem to have easy way to access community(group) menu with option to copy community URL for sharing. Also on Android possibly should be an option to copy community URL from the list of conversations/communities, not needing to be inside the group.

**Comment by KeeJef** [comment]
If you go into the community and press the hamburger menu there is an option to "Copy Community URL" this seems easy enough for me, were you suggesting another change?

**Comment by slrslr** [comment]
I think that the point was to have options like one mentioned, located in the overview - list of communities/conversations not needing to enter community or group where to option is according to you.
You are not always in the said community and i think that the habit in many apps is to manipulate/manage things in the overview, like it is in Desktop app where i right click item in the list of Conversations. Android app should have it too IMO.

**Comment by tashijayla** [comment]
I completely agree @slrslr 👍, when I got the update I thought that the ability to copy open group URLs Hadn't been added yet! because I couldn't see the option in the chats overview, it would definitely be more user friendly to have the option in the pop up menu when you hold on a community in the same place as the Session ID is when you hold on a normal chat conversation

**Comment by KeeJef** [comment]
This option has now been added into the long press menu
