### ISSUE TITLE
[Feature Request] Store on Swarm till reciepent recieves

### ISSUE THREAD

**Issue by natur960** [oxen-io/session-android#1128]
is it possible to add toggle for stoing on swarm only till retrieval by recpient ? like in signal, which also works with multi device (well only one mobile device allowed by signal and the rest non-handy's)?
 
 tnx

**Comment by KeeJef** [comment]
Due to the way multi device works a setting like this would prevent messages from being synced to linked devices, however we will be adding new settings in our disappearing message update (Disappear after send and disappear after read) which will allow for more fine tuning of how long a message remains on the swarm which would allow for similar functionality .
