### ISSUE TITLE
(Vulnerability) forward secrecy

### ISSUE THREAD

**Issue by qdhj** [oxen-io/session-android#1138]
As far as I undestrand, Session uses same encryption key for protecting bunch of messages. Each sent message should be protected by a _unique_ encryption key, so if the encryption key on the device is compromised, it doesn’t compromise past messages. Almost every other messenger (from Signal/Wickr Me/Wire to even FB messenger & Viber) has that, shall have Session also.

**Comment by KeeJef** [comment]
This was a design decision we made when developing the Session protocol you can look at our justifications [here](https://getsession.org/session-protocol-technical-information). TL;DR There are very few cases in Session where PFS would protect user messages, and because of our decentralised network structure deployment of PFS is much more fragile than the centralised services you listed
