### ISSUE TITLE
Longer voice messages (up to 10 minutes)

### ISSUE THREAD

**Issue by serrq** [oxen-io/session-android#1182]
I understand that we are perpetually struggling with bugs and new features, but one-minute voice messages do not help the cause that they should support.

I mostly getting voice messages truncated by the time limiter cleaver.
I therefore ask that this limit be extended to 10 minutes.

No more. I think ten minutes satisfies a large audience of people.

**Comment by tashijayla** [comment]
As I explained before Session is using onion request at the moment so it's currently not possible from my understanding to reliably send voice messages that are more than a minute long because it would be a larger File. When Lokinet is integrated into Session the file size limit will be increased and hopefully you will then be able to send voice messages much longer than 10 minutes ;-)

**Comment by sysfu** [comment]
Why can't the application by modified to encode the audio at a lower bit rate and greatly reduce the file size?

**Comment by tashijayla** [comment]
> Why can't the application by modified to encode the audio at a lower bit rate and thus greatly reduce the file size and increase the playable message length?

At the moment the voice messages sound good to me and I use them all the time because I have Dyslexia, I would have thought that if you lower the bit rate the audio would sound lower quality, which would make Session seem cheep if it couldn't do nice sounding voice messages. 

I think the Session devs should keep focusing on the root of the problem Which is the Session isn't using Lokinet yet, they should keep focusing on the big problems at the moment' you just need to look at the Screen and stop recording just before you think it's almost a minute I've gotten very used to it and find myself doing the same thing when I do voice messages on other apps as well now 😆, it will be strange and amazing when in the future you are able to do Longer voice messages

**Comment by sysfu** [comment]
> > Why can't the application by modified to encode the audio at a lower bit rate and thus greatly reduce the file size and increase the playable message length?
> 
> At the moment the voice messages sound good to me and I use them all the time because I have Dyslexia, I would have thought that if you lower the bit rate the audio would sound lower quality, which would make Session seem cheep if it couldn't do nice sounding voice messages.

I would much rather have functional but lower quality audio messages than the current setup where they cut off unexpectedly without informing the end user. At the very least the devs should put a one minute limit on the recordings so that people don't continue talking to themselves, mistakenly thinking that someone else will be able to heard the full recording. Terrible user experience.

**Comment by tashijayla** [comment]
> > > Why can't the application by modified to encode the audio at a lower bit rate and thus greatly reduce the file size and increase the playable message length?
> > 
> > At the moment the voice messages sound good to me and I use them all the time because I have Dyslexia, I would have thought that if you lower the bit rate the audio would sound lower quality, which would make Session seem cheep if it couldn't do nice sounding voice messages.
> 
> I would much rather have functional but lower quality audio messages. With the current setup they cut off unexpectedly without informing the end user. 
> 
> At the very least the devs should put a one minute limit or warning on the recordings. That way people don't continue talking to themselves while mistakenly believing they are still being recorded past the minute mark. 
> 
> Terrible user experience.



Very true 👍

**Comment by steveeJ** [comment]
* [session-android: stops recording after 1 minute](https://github.com/oxen-io/session-android/blob/7b0c0147917655c88782e21eb0321ab16671ad78/app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt#L1576)
* [session-desktop: 5 minutes (equals 1.97 MiB)](https://github.com/oxen-io/session-desktop/blob/9310b43394f82c84531c700d988f82be310a3c78/ts/session/constants.ts#L39-L41)

i just took a sample on android and i got 257KiB from a 55s long recording.
this would mean we could actually record 470s before the file exceeds 1.97MiB. this assumes a constant bitrate and i'm not sure that's realistic. it seems realistic to assume that upping the duration limit to 5 minutes on session-android would not exceed the 1.97MiB that seem applied on session-desktop.

**Comment by KeeJef** [comment]
Closing now that this has been increased to 5 mins

**Comment by sysfu** [comment]
> Closing now that this has been increased to 5 mins

Does the five minute limit apply to the iOS client as well? People I correspond with who are using the iOS client are routinely cut off without warning at the three minute mark.

**Comment by KeeJef** [comment]
> > Closing now that this has been increased to 5 mins
> 
> Does the five minute limit apply to the iOS client as well? People I trade voice messages with who are using the iOS client are routinely cut off without warning at the three minute mark.

Open a separate issue on Session iOS repo with that behavior and we can have a look into it
