### ISSUE TITLE
[Feature Request] Allow more granular times for `Disappearing Messages`

### ISSUE THREAD

**Issue by x80486** [oxen-io/session-android#1233]
## Code of Conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

## Description

This is a feature I used all the time. I can even put a global setting for it if it was available :wink:

At the same time, if possible, it would be great to configure the time, for instance, to a month. The proposal in some other applications look interesting. For instance, some of the ones I've seen they allow you to choose the date component: `months`, `weeks`, `days`, `hours`, `minutes`, `seconds`, and at the same time, there is a constrain with numbers that will let you finally set this — while putting the higher limits supported for each.

I think `6` months could be the _ultimate max_ allowed? Or perhaps `3` months?

**Comment by KeeJef** [comment]
We are currently in the process of updating disappearing messages so you will see some changes to disappearing message timers soon. However the longest supported timer will still remain at 2 weeks. This is because a message only exists on the swarm for a maximum of two weeks, so if a user sets a timer to 3 months, sends a message and the recipient doesn't receive that message it will disappear from the swarm after two weeks. 

In most cases this wont happen and the 3 month timer can be honored, since the recipient will receive the message before it expires at the swarm level, but this UX is quite hard to explain to the user. Hence our apprehension

**Comment by x80486** [comment]
> We are currently in the process of updating disappearing messages so you will see some changes to disappearing message timers soon. However the longest supported timer will still remain at 2 weeks. This is because a message only exists on the swarm for a maximum of two weeks, so if a user sets a timer to 3 months, sends a message and the recipient doesn't receive that message it will disappear from the swarm after two weeks.

Thanks for the update :wave:

I wonder if the two weeks restriction cannot be changed in the future, or is this a restriction from `Oxen` itself?

**Comment by KeeJef** [comment]
It can be changed, but there are some factors which should be considered before it would be changed, actually an issue was just opened recently here https://github.com/oxen-io/session-desktop/issues/2792
