### ISSUE TITLE
Let the user know if the account they're messaging still has the app installed / isn't inactive or redundant

### ISSUE THREAD

**Issue by RustoMCSpit** [oxen-io/session-android#1248]

**Comment by RustoMCSpit** [comment]
Obviously the account owner should choose if they're active status shows but I think if an account goes totally dormant as in the app was uninstalled it should alert current friends

**Comment by tashijayla** [comment]
I would love to see a optional feature allow contact to see when online.
Allow contact to see if I've connected to Lokinet in the past minute, hour, day, or week or 2 week period. By default I think it should show all contacts if you haven't connected to Lokinet in the past 2 weeks.

**Comment by KeeJef** [comment]
This would be tricky, since we would need to store something in the swarm which would indicate whether a user had app installed or account was redundant and this would expire after at most 30 days, so definition would be low. This metadata generally isn't something we would want to add to the app. Online status will be something we will look at again when Lokinet is integrated. Closing for now
