### ISSUE TITLE
When a user leaves a group, they still appear in the list of members, and cannot be added back

### ISSUE THREAD

**Issue by bohwaz** [oxen-io/session-android#1279]
**Code of conduct**

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

In a group, a user left as he deleted the app from his phone, and now wants to come back to the group.

Now they still appear in the list of group members. And when I go to "Add members", this user does not appear in the proposed list. So there is no way to add them back to the group.

Also,when I click an existing member in the list of members, it does nothing, even though the list item is clickable and reacts visually.

It's the same issue on the desktop app.

**Comment by KeeJef** [comment]
Closed groups are not in the best state currently, we are working on an overhaul, can you remove/kick the user and readd them?

**Comment by bohwaz** [comment]
No, the user has already left the group ("Name has left the group") so we can't remove them.

Also I don't have the "remove user from group" option for users on this group, maybe because I'm not the one who created the group?

**Comment by hjubb** [comment]
Yes I think only the admin can currently "fully remove" a user. This is because technically even if they send a "user has left" and stop polling for the group, until the admin rotates the group message encryption key, the user who has left will still technically be able to read the messages. To avoid a lot of race conditions and as a very basic permission system only a new encryption key will be accepted by group members if it was sent by the group admin. It is further complicated by the potential of having multiple devices as well, as there was not a great way to synchronize across the admin's potential multiple devices which one would create and forward the new encryption key to the group members. I think it would be inaccurate for user's to remove the user from the group list until the admin removes them and forwards a new encryption key.

As KeeJef mentioned, this will be fixed in the future but for now the admin has basically all the group remove / update encryption (automatic) ability.

**Comment by hjubb** [comment]
Would be great to get confirmation if the admin can remove the user and it works as described above, at which point we can probably close this one as it will be fixed in the improved groups

**Comment by bohwaz** [comment]
Yes as described, the admin could delete the user and re-add the user.

But we didn't even realize there was an "admin" for a group, and couldn't find a way to make other users admins as well.

Thank you.

**Comment by hjubb** [comment]
Currently, the admin is just the group creator, but in the future version of the groups the creator will be able to promote any other group member to share the admin role. I'll close this issue as deleting and re-adding from the admin fixed it by the sounds of it, although it might be a little unintuitive from the user perspective. Should be improved in the future groups version though :+1:
