### ISSUE TITLE
Why isnt' there a contact list/blackbook? Shouldn't be hard to implement right?

### ISSUE THREAD

**Issue by nolyoi** [oxen-io/session-android#475]
**Describe the bug**

/the current way of managing contacts is to keep the discussion window open which I find to be an awful idea for. a security/privacy app. 

**To reproduce**
Explains itseslf
Same as above

**Smartphone (please complete the following information):**

 - Device: [e.g. Samsung Galaxy S8]: Galaxy x10+
 - OS: [e.g. Android Pie]
 - Version of Session or latest commit hash: Latest from Google App Store (1.8.1)

**Additional context**
 
Having a contact book where you can set a name to an address would easily make this my #1 chat app. But, lacking his feature is killing it'd potential use cases for me ans a few others I know personally. Some conversations I'd like to delete wirhour refinding somond's Session ID toy know?

We just need a contacts to tab that shows Name set by me. Their chosen session name/ Session ID.

Being a soft engineer myself, I cant imagine this feature being too difficult to implement.

Is this in the roadmap? Will this be coming any time soon. It's my biggest gripe with the software after having used-it nearly since it relessed.

**Comment by PopeNobody** [comment]
I would suggest considering developing an interface, and possibly a reference implementation of a client, but loosely coupling it to Session so that people can plug in many different implementations.

My App, Cell 411, would probably implement this interface, as we are intending to use [ either Session or Oxen , I don't know which layer we will interface with ] as the session layer of our communications protocol, and remove our dependency on Google and/or Apple to deliver notifications to our users.

But some of our users will probably be very security conscious, and will want to limit the data stored and transmitted by the app.

Cell411, for example, might generate new addresses and communicate them out of band, in the same way that cryptocurrency wallets do, in order to limit the conclusions that can be reached by someone who captured the device.

**Comment by nolyoi** [comment]
> I would suggest considering developing an interface, and possibly a reference implementation of a client, but loosely coupling it to Session so that people can plug in many different implementations.
> 
> My App, Cell 411, would probably implement this interface, as we are intending to use [ either Session or Oxen , I don't know which layer we will interface with ] as the session layer of our communications protocol, and remove our dependency on Google and/or Apple to deliver notifications to our users.
> 
> But some of our users will probably be very security conscious, and will want to limit the data stored and transmitted by the app.
> 
> Cell411, for example, might generate new addresses and communicate them out of band, in the same way that cryptocurrency wallets do, in order to limit the conclusions that can be reached by someone who captured the device.

Makes sense, in that case though it could always be made into an optional feature. And you're not necessarily putting anyones data at risk, i store some session id's in a txt file because i hate having 20+ open. conversations in my app.

**Comment by nielsandriesse** [comment]
Hi @nolyoi, this is on our to do list. Everything's a matter of priorities though. There are some other issues we need to take care of first :) .

**Comment by KeeJef** [comment]
we now have essentially have a contacts list, which you can see by pressing the + button
