### ISSUE TITLE
Questions on programatic use of Session 

### ISSUE THREAD

**Issue by PopeNobody** [oxen-io/session-android#476]
I would like to enable a program I am working on to send Session messages, in the same way that apps can send SMS messages.

0) Is messaging by other apps a supported use case, or should this be done at the Oxen layer?

1) Is there a way that another app running on the users phone could programmatically send Session messages to other users?  

2) I know that Session uses Google and Apple push notifications.  I have found these to be less reliable than I would like, and, I don't trust these companies with our data.  If one was going to sever his relationship with Google and Apple, and still wanted to use Session, is there any conceivable way to have immediate delivery of emergency messages without killing the battery life of the phone?

3) Do you know of other projects that are attempting to user Session as infrastructure, or is this a first?  Is this the kind of thing that the Session authors would want to cooperate with, or do you think that Session is the wrong tool for the job?

**Comment by hjubb** [comment]
Hey @PopeNobody great Q's 

for q0 and q1 you could construct and send messages as long as they're in the right format, I know there is an existing library for JS that makes use of programmatically sending Session messages to others. for q2 it relates to how you would receive and poll for messages if you didn't use the google or apple push notifications, you could do background polling but that would still rely on on having to manually check, even periodically instead of getting things pushed to you. for q3 I have seen a project that uses Session to authenticate users / requests which you could use as 2fa. I'm sure there are a lot of ways to get more info on these sorts of projects and integrating something through the other community resources for Session or the community open groups where people are more active in discussion :+1:

**Comment by Sepero** [comment]
More information regarding q3 can be found here, open source push notification projects.

https://medevel.com/15-os-push-notification/

**Comment by PopeNobody** [comment]
> Hey @PopeNobody great Q's
> 
> for q0 and q1 you could construct and send messages as long as they're in the right format, I know there is an existing library for JS that makes use of programmatically sending Session messages to others. for q2 it relates to how you would receive and poll for messages if you didn't use the google or apple push notifications, you could do background polling but that would still rely on on having to manually check, even periodically instead of getting things pushed to you. for q3 I have seen a project that uses Session to authenticate users / requests which you could use as 2fa. I'm sure there are a lot of ways to get more info on these sorts of projects and integrating something through the other community resources for Session or the community open groups where people are more active in discussion +1

Thanks for the response!

I happened to notice it today.  For what it's worth, I have not had time to get signal involved in my project, and for the moment I am on Federal bail that forbids me to use any kind of crypto-currency, but I have been using websockets as a stand in for Google messages, and they work pretty well.  They would work much better if somebody who was an android and hardware efficiency expert ( I am far from either ) optimized the code for battery life.  But for somebody who degoogled their phone for a reason, it's worth the extra power drain.
