### ISSUE TITLE
QR code scanner doesn't read qr codes generated outside the app

### ISSUE THREAD

**Issue by rafirafirafi** [oxen-io/session-android#484]
**Describe the bug**

It looks like session is unable to start a session with a code that has been generated outside the app itself. Even though the qr contains the same information.

**To reproduce**

Steps to reproduce the behavior: generate a qr code of your session id with the qr code generator of your choice and try to start a session by scanning it

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: samsung s10e
 - OS: 11
 - Version of Session 1.8.1

**Additional context**

**Comment by hjubb** [comment]
is the app taking you anywhere after you scan the QR code, failing with a feedback message or just not doing anything or picking it up? I've just generated a plaintext QR code of a user's session ID that could scan successfully, it may have something to do with any additional data the generation process might be including or if nothing is happening at all the QR code might not be picked up due to not enough contrast, possibly other issues. Let me know if you've got any additional info for this one or if any of those suggestions help you get to the bottom of it

**Comment by Norbert80** [comment]
@rafirafirafi thanks for your report. However i am wondering... I regularly use "selfe-made" QR codes with session IDs and never experienced and issues. Could you please attache such a QR code here?

**Comment by nielsandriesse** [comment]
The QR code scanner inside Session is just meant for adding people. Changing this to a feature request.

**Comment by Norbert80** [comment]
For me scanning QR codes with Session IDs generated with conventional QR codes generators work without issues. I think this issue is invalid.

@nielsandriesse I suggest to close this issue.
