### ISSUE TITLE
"Note to Self" in Contact List on top

### ISSUE THREAD

**Issue by xbvrhlmb** [oxen-io/session-android#485]
I think "Note to Self" should be  on top in contact list, but now sort in Name Contact List

**Comment by invalid-error** [comment]
I would prefer both. Why not a press hold or right wipe to access a pin option. Pinned contacts show up at the top.

**Comment by x80486** [comment]
There is something I don't fully understand. This looks very much like a fork of `Signal`, and since `Signal` already have such feature implemented, why wouldn't `Session` get that feature automatically when the code is synchronized with the latest from `Signal`?

A very similar approach goes for most of the feature requests and bugs reported.

**Comment by eyeberic** [comment]
Because Session is a fork from the Signal code-base at a certain point in time (version), and branched out on its own. 

The changes made from Signal code-base don't get pushed down into Session branch, and vice versa from Session branch up into Signal. 

Anyway, this "Note to Self" can already be "Pin Conversation"-ed to maintain within top of the conversation list view.

**Comment by x80486** [comment]
> The changes made from Signal code-base don't get pushed down into Session branch, and vice versa from Session branch up into Signal.

Somehow I thought I saw in the Oxen website that `Session` was still using the `Signal` protocol, that's why it didn't make sense for me that this wouldn't rebase changes from `Signal`, but [there is](https://getsession.org/session-protocol-technical-information/) the `Session` protocol already!

This is great 🥳 ...and I'll stop spamming this thread 😎

> Anyway, this "Note to Self" can already be "Pin Conversation"-ed to maintain within top of the conversation list view.

By the way, where do you see that option to pin the "Note to Self" conversation? I'm on Android version `1.11.8 (2185)` and can't find a way to do that.

**Comment by eyeberic** [comment]
Sorry, my mistake. 

The "Pin Conversation" function is on Desktop, and is not yet on the Android client (1.11.8). 

For the devs to follow-up on this implementation.

**Comment by hjubb** [comment]
The ability to pin a chat to the top, with ordering based on the activity (among other pinned chats) is introduced in #806

**Comment by hjubb** [comment]
Does this satisfy the issue for you, at least temporarily @xbvrhlmb ? I think the user experience and design of forcing "note to self" at the top of the conversation list for every user might be too much, but I can see the ability to get to your own notes either through the new conversation or some sort of other shortcut to be very useful in the future as well :+1:

**Comment by xbvrhlmb** [comment]
@hjubb, Sorry I haven't seen it before.
You are the creators, I just suggested the idea)

my opinion is that "notes for yourself" should always be at the very top, that is, the first in the list

For example, a user can pin 10 dialogs, and since (relevance will take notes at the bottom, the user will have to look for them somewhere in the middle between pinned dialogs and regular dialogs

Therefore, I think that the very top will be much easier and more convenient, but for those who are uncomfortable with it, you can add the function to change it in the settings

**Comment by hjubb** [comment]
No worries @xbvrhlmb the feature has just been merged so it has not been put into a release yet. It may at the least improve the experience for you when it does arrive in a release. There could be room to improve the ability to get to your notes similar to how you've described, or even through some other user interface shortcut that would allow you to always get to the notes in an easy way

**Comment by xbvrhlmb** [comment]
great, I don't have any more ideas on this plan yet. I will be waiting for an update)

**Comment by hjubb** [comment]
You can now access the notes to self in the top of the search menu when you haven't typed anything in version 1.11.16, you can also pin the notes to self on your main chat list. I hope this addresses the issue for everyone :+1:
