### ISSUE TITLE
the encrypted data can be recover with access to the phone

### ISSUE THREAD

**Issue by gilojimjim** [oxen-io/session-android#489]
If you have access to a phone (ios or android) you can copy the fixed keys and decrypt all the data stored in the phone. the keys should be encrypted with an user password. 

The public and private keys are stored unencrypted on the phone, you should include them in the signal.db and encrypt this database with an user password.

You use fixed key to encrypt attachments : pref_attachment_encrypted_secret
fixed key to encrypt the log : pref_log_encrypted_secret
fixed key to encrypt the database : pref_database_encrypted_secret

the database should be encrypted with an user password, same for attchments and same for the logs.

when access to phone, the keys can be recovered and use to decrypt all the data.

**the files :**

**/data/data/network.loki.messenger/no_backup**

**com.google.InstanceId.properties**

Contains private and public key NOT ENCRPYTED !! all theses keys should be encrypted with an USER PASSWORD !

#Thu Mar 18 20:17:44 GMT+01:00 2021
**pri**=MIIEvQIBADANBgkCUT (cut key too long...)
**cre**=1616095064403
**pub**=MIIBIjCUT (cut key too long...)

**/data/data/network.loki.messenger/shared_prefs**

contains fixed key which can be used to decrypt data. all this keys should be ENCRYPTED with an user password !

**com.google.android.gms.appid.xml**

<version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <name="**|S|cre"**>1616095064403</string>
    <name="|**S||P|**">MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvLbwV-62q94ki4CHPsI4- CUT</string>
    <name="**|S||K|**">_Xk5t4efJEbGb7BLflOHqdigcmLplMhPNQcUsKuFK0_CUT</string>
    <name="|T|43512467490|*">{&quot;token&quot;:&quot;faosk7Of4jI:APA91bEALEgZ-CUT &quot;,&quot;appVersion&quot;:&quot;1445&quot;,&quot;timestamp&quot;:1616095065518}</string>
</map>

**network.loki.messenger_preferences.xml**

<version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <name="SELECTED_UI_MODE">SYSTEM_DEFAULT</string>
    <name="last_experience_version_code" value="144" />
    <name="restoration_time" value="0" />
    <name="pref_seen_welcome_screen" value="true" />
    <name="pref_is_using_fcm" value="true" />
    <name="pref_fcm_token">faosk7Of4jI:APA91bEALEgZCUT</string>
    <name="last_version_code" value="144" />
    <name="pref_last_configuration_sync_time" value="1616698794264" />
    <name="pref_last_profile_update_time" value="1616698790439" />
    <name="pref_backup_next_time" value="1616784539876" />
    <name="pref_notification_channel_version" value="2" />
    <name="pref_local_registration_id" value="7705" />
    <name="pref_typing_indicators" value="true" />
    <name="pref_read_receipts" value="true" />
    <name="last_snode_pool_refresh_date" value="1616698233395" />
    <name="**pref_attachment_encrypted_secret**">{&quot;data&quot;:&quot;CUTysVEgUeLRqGA5FhLxpw/hQUB+Cm6rMn+nm69c3H4VK&quot;,&quot;iv&quot;:&quot;T2sseYfBwDd4BmWj&quot;}</string>
    <name="pref_configuration_synced" value="true" />
    <name="pref_last_fcm_token_upload_time_2" value="1616698154143" />
    <name="pref_disable_passphrase" value="true" />
    <name="pref_profile_key">CUT=</string>
    <name="**pref_log_encrypted_secret**">{&quot;data&quot;:&quot;zLXtJfw/amB3F1PmeAXZgjR05ZTJJl8QQwFtfCUTEQu6&quot;,&quot;iv&quot;:&quot;GkgNuEC5mtnN5Bf0&quot;}</string>
    <name="has_viewed_seed" value="true" />
    <name="pref_local_number">05e6cfabc7b3977e4cb26ff77aa9f3050cff170401c8af767e8c93a4a745b1082c</string>
    <name="**pref_database_encrypted_secret**">{&quot;data&quot;:&quot;T2g87/CUT&quot;,&quot;iv&quot;:&quot;+ojTKLzu/DDc/sCw&quot;}</string>
    <name="pref_profile_name">Loju</string>
</map>

**SecureSMS-Preferences.xml**

<version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <name="**pref_identity_private_v3**">eNTDTubeYx8Q8zGCUT=</string> (key cut)
    <name="loki_seed">09cfb94b6fc7930107438fb95fc58434</string>
    <name="**pref_identity_public_v3**">BebPq8ezl35Msm/3eqnzBQz/FCUTs</string> (key cut)
    <name="**pref_ed25519_secret_key**">Cc+5S2/HkwEHQ4+5X8WENAAAAAAAAAAAAAAAAAAAAADq0rvnllu8OmCUT==</string> (key cut)
 <name="**pref_ed25519_public_key**">6tK755ZbvDphSSEBdNy5eVSiyGCUT=
</map> (key cut)

**Comment by hjubb** [comment]
I believe the first preferences linked are related to a google / firebase service and not controlled by Session itself. The "encrypted secrets" in the messenger_preferences are stored encrypted and are using Android's in-built KeyStore for devices running Android 6.0 and above, not the actual encryption keys. Will have to take more of a look at the identity stuff

**Comment by M09NST3R** [comment]
Thank you for you "audit", sir. Also saw your other Issue. Great work. @gilojimjim

**Comment by jimgillo** [comment]
The ed25519_secret_key is store in plaintext on the phone.
You should add all this keys into the sqlite.db database and allow the user to encrypt it with a password.

**Comment by nielsandriesse** [comment]
Hi @gilojimjim, this topic has been brought up before. Let me address some of the points you're raising because not all of them are correct. 

Session inherits the way it encrypts attachments, logs and the database from Signal. The way it works is like this: `pref_attachment_encrypted_secret`, `pref_log_encrypted_secret` and `pref_database_encrypted_secret` are * not * directly the keys used to encrypt attachments, logs and the database. Each of these is itself encrypted with a random key, which is stored in the device key store. This is why each of these preferences has the `_encrypted` part in its name (they're the encrypted values). Storing application secrets in the device key store is recommended security practice.

Regarding the X25519 and ED25519 key pairs stored under `pref_identity_private_v3`, `pref_identity_public_v3`, `pref_ed25519_secret_key` and `pref_ed25519_public_key`, this is again inherited from Signal. We could encrypt these with a password set by the user and that's something we'll probably do. That said though, one can only get access to these values if your device has been both confiscated AND unlocked.

**Comment by jimgillo** [comment]
I think you should move
pref_attachment_encrypted_secret
pref_log_encrypted_secret
pref_database_encrypted_secret
pref_identity_private_v3
pref_identity_public_v3
pref_ed25519_secret_key
pref_ed25519_public_key

inside the signal.db database and allow the user to encrypt it with an user password.
It's easier to move them into the signal.db and allow to encrypt it with a password.

>Each of these is itself encrypted with a random key, which is stored in the device key store

yes i know but you know that this is not a problem to access the keystore on IOS or Android if someone has access to the phone :

https://blog.elcomsoft.com/2019/08/how-to-extract-and-decrypt-signal-conversation-history-from-the-iphone/

https://blog.elcomsoft.com/2020/04/forensic-guide-to-imessage-whatsapp-telegram-signal-and-skype-data-acquisition/

In order to decrypt Signal conversation databases extracted from the iPhone via file system acquisition, you will also need to extract the encryption key from the keychain. If you are using [Elcomsoft iOS Forensic Toolkit](https://www.elcomsoft.com/eift.html), make sure to capture the keychain along with the file system image.

To decrypt and analyze a Signal conversation history, open the file system image in [Elcomsoft Phone Viewer](http://www.elcomsoft.com/epv.html) and use the extracted keychain file to decrypt the Signal database. Elcomsoft Phone Viewer will then decrypt the database and display its content in a blink of an eye.

**Comment by xanoni** [comment]
@jimgillo wouldn't this require an unlocked phone? Aka, you are screwed anyway?

**Comment by jimgillo** [comment]
no, the phone can be unlocked without knowing the code through security holes. this is how elcomsoft and thatbrite work. while a user password protects the data even if there are security holes in the phone

**Comment by xanoni** [comment]
> no, the phone can be unlocked without knowing the code through security holes. this is how elcomsoft and thatbrite work. while a user password protects the data even if there are security holes in the phone

Which security holes are you referring to? You mean the ones for old phones (e.g., iPhone 4), or stuff that affects newer models as well?

My understanding is that these vulnerabilities only exist in old hardware that few people use at this point.

**Comment by jimgillo** [comment]
>Which security holes are you referring to? You mean the ones for old phones (e.g., iPhone 4), or stuff that affects newer models as well?

No, new models.
Checkm8 for example :
https://checkm8.info/

Or blackbird:
https://www.imore.com/apples-t2-chip-has-critical-unpatchable-security-flaw-says-researcher

**Comment by xanoni** [comment]
@jimgillo Out of curiosity, what are the prerequisites for this to work? E.g., would it also work after a fresh reboot without the PIN ever entered?

**Comment by jimgillo** [comment]
***@***.***(https://github.com/jimgillo) Out of curiosity, what are the prerequisites for this to work? E.g., would it also work after a fresh reboot without the PIN ever entered?

> it's a hardware flaw, nothing to do with the operating system. there is therefore no prerequisite nor any remedy.

**Comment by nielsandriesse** [comment]
Update on this: the next version (1.11.3) will encrypt the identity keys with a key held in the device's key store. Adding the ability to use a user-specified password rather than an auto-generated key held in the device key store is on the roadmap. 

Going to close this for now :)
