### ISSUE TITLE
Direct messaging to group members not possible

### ISSUE THREAD

**Issue by Norbert80** [oxen-io/session-android#517]
From Telegram and recent versions of Signal users are used to click on avatar images (on the left side of messages) in order to contact participants privately.
The current solution with the key button that copies IDs into clipboard is not intuitive. That's why people I have migrated to Session always ask me how to contact group members directly.

I suggest to change Session in the same way so that a click on an avater initiates a private massage.

Android build 1.9.1.

**Comment by hjubb** [comment]
this is a good idea, maybe a feature suggestion label instead of a bug label?

**Comment by Norbert80** [comment]
> this is a good idea, maybe a feature suggestion label instead of a bug label?

I agree. But I don't know how to or if I have these privileges at all.

**Comment by hjubb** [comment]
ah okay, I wasn't sure if that was in your control or if the existing `bug` label was auto-added by default somehow

**Comment by Norbert80** [comment]
Signal Android has that function. Can the code be taken from there?

**Comment by Norbert80** [comment]
@nielsandriesse thanks for the info and work on that great project.

Regarding this issue I would like to note, that with the GUI polishing the key-button has been removed (which is the right decision).
However since, the function demanded in this issue is not yet implemented, since v1.11.0/1 we have no way (work around via key button more possible) to contact group members with direct messages. So the priority should be raised and targeted to next release.

**Comment by Norbert80** [comment]
@nielsandriesse I just found that Android build 1.11.5 has implemented a sliding popup when clicking on profile pictures within group chats. This slider contains a field that displays the contact's ID as well as a Copy button.

It would be great to complete/polish the GUI with the following to changes:

- Add a second button to the slider to open a direct chat to the contact. (The desktop client has such a button. This makes it more comfortable because there is no need to copy and paste IDs.)

- Remove the menu item "Copy Session ID" from the ... menu of selected messages. The ID is already available in the slider. So there is no need anymore for this menu item.

**Comment by eyeberic** [comment]
I have a different notion, though not sure if anyone else shares the same. 

Usually when I tap on another user's avatar, it is usually with the intention of having a 1-to-1 chat. 
This is especially true when the original setting is a multi-user group. 

My motive is for the "Copy" button to just be replaced with a "Message this User" button, similar to what the Desktop client currently has (Start New Conversation). 

In fact, the "Copy" button in the slider pop-up, and the "Copy Session ID" option after long-tap on a message, are redundant, at least for Android devices, because it can already be done by long-tap on the Session ID, in the slider pop-up, after you tap on the user's avatar.

**Comment by Norbert80** [comment]
@eyeberic thanks for that patch! I have tried v1.11.9 and can confirm that it works as expected.

**Comment by hjubb** [comment]
Awesome news @Norbert80 !
