### ISSUE TITLE
Remove metadata upon saving/uploading content.

### ISSUE THREAD

**Issue by Flam3z** [oxen-io/session-android#614]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

Upon saving an image from session the metadata is still present. Showing which app the image was saved from, the year it was saved among other information filled into the file name. Removing metadata upon uploading or saving things is a must for session as I thought metadata was already remove by default thus, increasing privacy.

**Comment by ianmacd** [comment]
Session doesn't expose metadata related to your message.

The body of any message you send, however, is data as far as Session is concerned. If that message includes an image attachment with a populated EXIF header, it is still data, not metadata, from the perspective of the transport mechanism.

Opinions on this may differ, but I strongly believe that no messaging client has any business inspecting my attachments and selectively mangling them. To do so would be to nanny the user and violate the principle of least surprise.

It's Session's job to send messages intact whilst not leaking any metadata related to the actual communication. What's in the message itself is nobody's business, including Session's. If the user wants the EXIF header stripped, it's up to the user to strip it before he sends it.

Otherwise, it's a slippery slope. Where does the nannying end? PDFs? .doc?

You wouldn't expect the postal service to open your letters and modify the contents, so why would you want Session to do it? Both cases would represent a serious violation of the user's trust.

**Comment by Flam3z** [comment]
> Session doesn't expose metadata related to your message.
> 
> The body of any message you send, however, is data as far as Session is concerned. If that message includes an image attachment with a populated EXIF header, it is still data, not metadata, from the perspective of the transport mechanism.
> 
> Opinions on this may differ, but I strongly believe that no messaging client has any business inspecting my attachments and selectively mangling them. To do so would be to nanny the user and violate the principle of least surprise.
> 
> It's Session's job to send messages intact whilst not leaking any metadata related to the actual communication. What's in the message itself is nobody's business, including Session's. If the user wants the EXIF header stripped, it's up to the user to strip it before he sends it.
> 
> Otherwise, it's a slippery slope. Where does the nannying end? PDFs? .doc?
> 
> You wouldn't expect the postal service to open your letters and modify the contents, so why would you want Session to do it? Both cases would represent a serious violation of the user's trust.

When you put it that way I now understand the principals of it and your analogy really helped settle that case, thank you.

**Comment by myfirstnameispaul** [comment]
> Session doesn't expose metadata related to your message.
> 
> The body of any message you send, however, is data as far as Session is concerned. If that message includes an image attachment with a populated EXIF header, it is still data, not metadata, from the perspective of the transport mechanism.
> 
> Opinions on this may differ, but I strongly believe that no messaging client has any business inspecting my attachments and selectively mangling them. To do so would be to nanny the user and violate the principle of least surprise.
> 
> It's Session's job to send messages intact whilst not leaking any metadata related to the actual communication. What's in the message itself is nobody's business, including Session's. If the user wants the EXIF header stripped, it's up to the user to strip it before he sends it.
> 
> Otherwise, it's a slippery slope. Where does the nannying end? PDFs? .doc?
> 
> You wouldn't expect the postal service to open your letters and modify the contents, so why would you want Session to do it? Both cases would represent a serious violation of the user's trust.

The reason privacy apps should default to stripping metadata is because *adding* metadata is the default for nearly all applications and hardware.

**Comment by ianmacd** [comment]
> The reason privacy apps should default to stripping metadata is because _adding_ metadata is the default for nearly all applications and hardware.

Session can't know the user's intentions, so it should treat him as intelligent, not stupid.

Any program that silently modifies the payload it is instructed to send is overstepping its bounds, patronising the user, and violating the integrity of the data it is charged with transporting intact.

Any metadata filtering applied to the payload should be explicit, optional, very well documented, and completely reliable. It was none of those things at the time this issue was opened. Whether that situation persists today I couldn't say, as I abandoned the Session platform in December 2023.
