### ISSUE TITLE
Message duplication in open groups

### ISSUE THREAD

**Issue by JustVictor17** [oxen-io/session-android#667]
**Code of conduct**

- [✓ ] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**
Cannot see wich of my replies got marked by other users

**To reproduce**
1. Write something interesting about lokinet to catch mods attention hehe...
2. Mods bite your bait and reply marking your bait reply
3. You can't see wich of your baits did work and therefore making it more difficult to make more convincing bait.
4. You get lonely and without frends :'(

**Screenshots or logs**

![Screenshot_20210719-011905](https://user-images.githubusercontent.com/87635958/126116184-416ee32d-c0e1-4bf3-9f34-7ac84415cae8.png)

**Smartphone (please complete the following information):**

 - Device: I don't know who manufactered the phone, it's brand is Bitel B9505
 - OS: Nougat 7.0 (sdk24)
 - Version of Session or latest commit hash: 1.11.4

**Additional context**

Please fix so I can get more baity
Also the issue element is Ghost and I recomend catching them with a Super Ball

**Comment by Sepero** [comment]
![Screenshot_20210721-234452__01](https://user-images.githubusercontent.com/1575546/126527185-a9bee998-6bbc-41c5-b40c-0ee435407863.jpg)


The title of this issue should be, "Original Message Not Found Bug"

The issue here is as follows. Person A sends message. Person B replies to that message (using the message reply feature). Person A sees a reply to "Original message not found"

It could be Person A replying to themselves also.

It's an extremely common bug, and happens with messages sent just minutes before replying

**Comment by JustVictor17** [comment]
Since this is a duplicate of Sepero already reported bug, I'm gonna close this, though the message duplication is still a Client bug on 1.11.4 I'll assume that it was already fixed on 1.11.5

**Comment by Sepero** [comment]
No, I reported a separate bug. This duplicate message bug still persists.
