### ISSUE TITLE
The sharing contact list order disordered

### ISSUE THREAD

**Issue by iqgustavo** [oxen-io/session-android#788]
**Code of conduct**

- [ ] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**
I have found probably an error on **android session** ... when sharing from another app like youtube, first appear the groups and then the contacts in alphabetical order ... **and then other contacts** in alphabetical order ... (why not all contacts are in alphabetical order?)

**To reproduce**
Open Youtube video
**click share to session**
**there is the contact list with what seems wrong order**

**Screenshots or logs**
None

**Smartphone (please complete the following information):**
Xiaomi Poco F2Pro **Android 11** RKQ1.200826.002 MIUI 12.5.2 
**Session 1.11.11**

**Comment by hjubb** [comment]
Thanks @iqgustavo this is probably an opportunity for a feature improvement, I'm sure there's a lot better ways that make sense to display this information, whether they're all grouped or whether it's based on recent activity and having some sort of filter / search in that list would be nice, I'll turn this into a feature-request so that people can add any ideas they have :+1:

**Comment by KeeJef** [comment]
This has been fixed, share list is now split into (Open groups, closed groups and contacts) all sorted alphabetically, would be cool if we could pin "note to self" at the top as well

**Comment by KeeJef** [comment]
Closing this as this list is now properly ordered, we will be making a change to pin note to self at top internally

**Comment by iqgustavo** [comment]
Thank you!
