### ISSUE TITLE
No ringtone in Android 6

### ISSUE THREAD

**Issue by tyuby** [oxen-io/session-android#819]
**Ringtone missing in Android 6**

I checked p2p calls v1.12.0 on three devices: Android 10 (1 thing Huawei HY5p) and Android 6 (2 thing Huawei BG2-W09).
6 > 10 the ringtone on Android 10 plays fine and in the system settings of Android 10 I can even select the ringtone
_Settings > Sounds & vibrations > Phone ringtone > Sounds …_
10 > 6 and 6 > 6 connection occurs, but on Android 6 there is no call signal, full silence. Although the call comes and I can answer. There is no corresponding setting in the system settings of Android 6 for sounds. There are no settings in the app also (yet).

**My propose**

By analogy with the Blabber (Jabber client; and there the call signal is sounded normally in both directions), I propose to do this setting in the messenger settings
_Settings > Notifications > Ringtone …_
Interestingly, this Blabber setting is present in Android 6, but not in Android 10, in same release.

**Labels**: _bug, improvement, feature-request_.

**Comment by tyuby2** [comment]
Deal wasn't about Android. The problem is solved in 1.17.1 thanks to a separate build for Huawei devices. Issue can be closed.

'Only install Huawei APKs if you want the Huawei pushes and dependencies in your application, as it replaces the Google / Firebase-based pushes for fast mode'

Offtopic. I'm writing from another account, because Github blocked tyuby for passivity. It requires confirmation via email, but that email service has died and I cannot do confirming. A great example of the unreliability of centralized services. Both email and github.

**Comment by KeeJef** [comment]
Great

**Comment by tyuby2** [comment]
Unfortunately, I was in a hurry with my report. I was inspired by the appearance of a separate assembly for Huawei and the check was completed in a hurry. I had limited time and was I was inattentive.

Later I did a detailed test on three Huawei devices (Android 10, 10, 6) and was disappointed. The picture remained unchanged. If the screen is active, then the voice call ringer sounds immediately, everything is Ok (I was in this situation the first time I checked). But if the screen is turned off (device is in doze), then the device is a dead brick and no notifications are accepted.

Moreover, I discovered that Session on Android 6 no works now (earlier it worked). Regardless, this is a universal building or an building for Huawei. It slows down and closes.

Problem with notifications in doze mode is not a Session problem, this is a large problem of devices. I found several links on this topic
https://developer.android.com/training/monitoring-device-state/doze-standby
https://censorship.no/user-manual/en/browser/bridging.html#how-to-become-a-ceno-bridge
https://dontkillmyapp.com/

Starting from Android 6.0, Android introduces two power-saving features -  Doze and App Standby. These functions in themselves are not a problem, because on a number of devices (for example Nokia) Session works great. This is my practice, I use Session on my Nokia smartphone every day.

But a particular device may also include its own power-saving features which are aggressive and may interfere with apps. They cannot be disabled using standard settings. According to the Don't kill my app! resource, Huawei devices are in the red zone of such risk.

Xiaomi is also located there, I tested Xiaomi on 3-4 devices. The result was the same everywhere, even with the presence of Google services - the call is announced only by vibration. No settings helped. Xiaomi is in the red zone of risk too.

Perhaps there is no need to spend too much time on specific devices, but it is enough to make recommendations on the undesirable types of devices for Session.

For example. 'Session will not work properly with devices: Huawei, Xiaomi, etc. Namely: it will not be possible to receive a voice call, notifications in Fast Mode will not work; otherwise there will be no problems. If receiving text and voice messages without notification is sufficient for your (you will have to check your messenger periodically), then otherwise these devices will work fine with Session. Outgoing calls are made without problems.'

**Comment by tyuby2** [comment]
I'm diving into the details.
Still, the call in Doze mode to Huawei goes through. But there is a nuance that confused me.

If the application window was not swiped out before switching to Doze mode (it was not removed from the screen), then the call to Huawei goes through 100%. But if you swipe out the application window before switching to Doze mode, then the call to Huawei sometimes goes through, but more often it doesn’t. I didn't catch the pattern. Maybe 50/50.

I always swipe out the application window, the application remains in the background, but does not clog the screen. I do this automatically.
 
In Nokia this does not create a problem for the Session, but in Huawei it turns out that in order to reception a call 100%, the application window cannot be swiping out before switching to Doze mode. That's it...

However, Huawei devices is now in use and knowing the nuance, you can receive calls on it.

**Comment by KeeJef** [comment]
Looking into this further this week

**Comment by KeeJef** [comment]
We made some fixes to the push notification server last week, notifications should be coming through more reliably now
