### ISSUE TITLE
All the messages I received and sent since april came back to the phone, more than 100 msgs.

### ISSUE THREAD

**Issue by Gaotu07** [oxen-io/session-android#916]
**Code of conduct**

- [ X ] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

After the update, all the messages I received and sent since april came back to the phone, more than 100 messages, including from contacts that were no longer in my contact list.

Where are these messages stored?  On the network or in some file on the phone?  How to trust the app if it's the fourth or fifth time this happens?  My employees are very afraid of the application and no longer trust the secrecy of messages, it is difficult to explain to basic users that third parties do not have access to these messages, but even I, who have an advanced degree of knowledge, am already suspicious of the secrecy of information .  Please explain this and a solution so that this does not happen again.  Thank you and good luck.

**Smartphone (please complete the following information):**

 - Device: S22 Ultra
 - OS: Last
 - Version of Session: 1.13.6 (2875)

**Comment by KeeJef** [comment]
So there's a few things that could be going on here 

1. Messages will be restored if they were sent less than 14 days ago if a new device is linked or a device is restored from seed, this will happen so long as the message was not explicitly deleted (exception for disappearing message until we fix that issue, see #407)
2. We did see a temporary issue with iOS clients which meant that messages were not correctly deleted from the local database and during a database migration would reappear. 

Outside of this though, messages older than 14 days should never reappear, since there is nowhere for them to reappear from, Service Nodes clear messages after 14 days so messages should never restore. Open groups will mostly store messages longer than 14 days but this wont affect 1-1 and closed group messages. 

If this issue is still occurring id be keen to get device logs to see if we can track down this issue.

**Comment by KeeJef** [comment]
Closing to be tracked in #407
