### ISSUE TITLE
Feature Request: Only me mentions

### ISSUE THREAD

**Issue by User1l0** [oxen-io/session-android#968]
Make able to set as default for all groups to enable only mentions that is addressed only to you. Without it session bombards you with messages from all chats.

**Comment by GameOverFlowChart** [comment]
It is already possible by long pressing on a group, but if you mean that that should be the default setting than I agree. Atleast for open groups only mentions as default makes much more sense. And having that bell with an @ sing on all open groups just looks ugly.

**Comment by hjubb** [comment]
This might be a sensible default option for the Session official open groups, but I think it might be too hard to say whether the mentions only notifications as a default make sense in other open groups. We can probably look to implementing this across all platforms as the default in future if it makes sense

**Comment by GameOverFlowChart** [comment]
> 

I think it is a sensible default option because I imagine communities as public space. If you are in a public cafe you would be overwhelmed if you would hear everyone talking, no? Your brain filters out the noise you only hear the ones who directly talk to you. This could be complemented with an @all feature for mods in case that it doesn't exist already. Not sure if I should open a new issue at this point since this one is somewhat ambiguous.
