### ISSUE TITLE
F-Droid: The upstream source code is not entirely Free

### ISSUE THREAD

**Issue by vrde** [oxen-io/session-android#976]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

On F-Droid, Session has one anti-feature that is "F-Droid: The upstream source code is not entirely Free".

Well I guess it's bug :) if not, which parts are not free?

Go here https://f-droid.org/en/packages/network.loki.messenger.fdroid/

If applicable, add screenshots or logs to help explain your problem.

![image](https://user-images.githubusercontent.com/134680/191933506-4bef3ad0-b035-4c30-8bf2-321c8f649f43.png)

**Smartphone (please complete the following information):**

**Comment by hjubb** [comment]
I think this is due to dependencies which are automatically picked up (relying on google services or firebase for notifications for instance). This is also a report for the non official version of this app that someone else has submitted to F-Droid so I'm not sure if they have manually defined it and have their own criteria as well
